spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 39.98.152.206
    port: 5672
    username: root
    password: root
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /root
    listener:
      simple:
        acknowledge-mode: manual #开启手动Ack